{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "53a3b86d_fb061818",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 7,
      "author": {
        "id": 1116294
      },
      "writtenOn": "2022-03-23T20:38:51Z",
      "side": 1,
      "message": "Fix another python conversion error in win_helper.py.\n\nFollowup to crrev.com/c/3547036",
      "range": {
        "startLine": 7,
        "startChar": 0,
        "endLine": 7,
        "endChar": 60
      },
      "revId": "1de97dfca17b9247da13bdf5b26e5854283da2c0",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}